# Generated by Django 3.0.6 on 2020-07-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20200727_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_skills',
            name='Field',
            field=models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end')], max_length=10),
        ),
        migrations.AlterField(
            model_name='web_skills',
            name='Text',
            field=models.TextField(max_length=1000),
        ),
    ]
