# Generated by Django 3.0.6 on 2020-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20200727_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(choices=[('Back-end', 'Back-end'), ('Game-dev', 'Game-dev'), ('Front-end', 'Front-end')], max_length=10)),
                ('Text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='web_skills',
        ),
    ]
