# Generated by Django 3.0.6 on 2020-07-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20200727_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='Field',
            field=models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('Game-dev', 'Game-dev')], max_length=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Text',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.languages')),
            ],
        ),
    ]
