# Generated by Django 3.0.6 on 2020-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20200728_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='Name',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='Name',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='technologies',
            old_name='Name',
            new_name='Text',
        ),
        migrations.AlterField(
            model_name='skills',
            name='Field',
            field=models.CharField(choices=[('Game-dev', 'Game-dev'), ('Back-end', 'Back-end'), ('Front-end', 'Front-end')], max_length=10),
        ),
    ]
