# Generated by Django 3.1 on 2020-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Name',
            new_name='Text',
        ),
        migrations.AlterField(
            model_name='skills',
            name='Field',
            field=models.CharField(choices=[('Back-end', 'Back-end'), ('Game-dev', 'Game-dev'), ('Front-end', 'Front-end')], max_length=10),
        ),
    ]
