# Generated by Django 3.1 on 2020-08-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_auto_20200829_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='Field',
            field=models.CharField(choices=[('Game-dev', 'Game-dev'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], max_length=10),
        ),
    ]
