# Generated by Django 3.1 on 2020-08-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_auto_20200829_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='Field',
            field=models.CharField(choices=[('Back-end', 'Back-end'), ('Game-dev', 'Game-dev'), ('Front-end', 'Front-end')], max_length=10),
        ),
    ]
